name: transfer-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Core scientific stack with OpenBLAS (no MKL)
  - nomkl
  - numpy<2  # PyTorch requires NumPy 1.x for compatibility
  - scipy
  - matplotlib
  - pandas
  - h5py
  - pillow
  - tqdm
  - colorama
  - tornado
  - pyyaml
  - scikit-learn
  - numexpr
  # PyTorch from conda-forge (CPU, generic build with OpenBLAS)
  - pytorch
  - torchvision
  - torchaudio
  - pip
  
  # Pip-only (not reliably provided/pinned via conda)
  - pip:
      - mat73==0.65
      - munkres==1.1.4
      - pymatreader==1.1.0
      - xmltodict==0.14.2
      - setuptools==80.9.0
      - wheel==0.45.1
      - wandb>=0.16.0
